import {
	mdiAccountCircle,
	mdiMonitor,
	mdiGithub,
	mdiLock,
	mdiAlertCircle,
	mdiSquareEditOutline,
	mdiTable,
	mdiViewList,
	mdiTelevisionGuide,
	mdiResponsive,
	mdiPalette,
	mdiReact,
	mdiShield,
	mdiAccount,
} from "@mdi/js";
export default [
	{
		show: true,
		to: "/",
		icon: mdiMonitor,
		label: "Dashboard",
	},
	{
		show: hasPermission('view role'),
		to: "/role",
		label: "Role",
		icon: mdiShield,
	},
	{
		show: hasPermission('view user'),
		to: "/user",
		label: "User",
		icon: mdiAccountCircle,
	},
	{
		show: true,
		to: "/table",
		label: "Table",
		icon: mdiTable,
	},
	{
		show: true,
		to: "/role/form",
		label: "Form",
		icon: mdiSquareEditOutline,
	},
	{
		show: false,
		to: "/ui",
		label: "UI",
		icon: mdiTelevisionGuide,
	},
	{
		show: false,
		to: "/responsive",
		label: "Responsive",
		icon: mdiResponsive,
	},
	{
		show: false,
		to: "/",
		label: "Styles",
		icon: mdiPalette,
	},
	{
		show: false,
		to: "/profile",
		label: "Profile",
		icon: mdiAccountCircle,
	},
	{
		show: false,
		to: "/login",
		label: "Login",
		icon: mdiLock,
	},
	{
		show: false,
		to: "/error",
		label: "Error",
		icon: mdiAlertCircle,
	},
	{
		show: true,
		label: "Dropdown",
		icon: mdiViewList,
		menu: [
			{
				show: true,
				to: "/error",
				label: "Item One",
				icon: mdiAlertCircle,
			},
			{
				show: true,
				to: "/error",
				label: "Item Two",
				icon: mdiAlertCircle,
			},
		],
	},
	{
		href: "https://github.com/justboil/admin-one-vue-tailwind",
		label: "GitHub",
		icon: mdiGithub,
		target: "_blank",
	},
	{
		href: "https://github.com/justboil/admin-one-react-tailwind",
		label: "React version",
		icon: mdiReact,
		target: "_blank",
	},
];
